/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Control.Validaciones;

/**
 *
 * @author omard
 */
public class UI_Principal extends javax.swing.JFrame {

    /**
     * Creates new form UI_Principal
     */
    
    Validaciones v = new Validaciones();
    
    
    public UI_Principal() {
        initComponents();
        setLocationRelativeTo(null);
        v.ValidaSoloLetras(Jt_Nombre);
        v.ValidaSoloLetras(Jt_Apellidos);
        v.ValidaSoloLetras(Jt_Usuario);
        v.valodarSoloNumeros(Jt_Cedula);
        v.valodarSoloNumeros(Jt_Telefono);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_Datos = new javax.swing.JTable();
        Jl_Buscar = new javax.swing.JLabel();
        Jt_Buscar = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        Jl_Foto = new javax.swing.JLabel();
        Btn_SubirFoto = new javax.swing.JButton();
        Jl_Cedula = new javax.swing.JLabel();
        Jt_Cedula = new javax.swing.JTextField();
        Jl_Nombre = new javax.swing.JLabel();
        Jt_Nombre = new javax.swing.JTextField();
        Jl_Apellidos = new javax.swing.JLabel();
        Jt_Apellidos = new javax.swing.JTextField();
        Jt_Correo = new javax.swing.JTextField();
        Jl_Correo = new javax.swing.JLabel();
        Jl_Telefono = new javax.swing.JLabel();
        Jt_Telefono = new javax.swing.JTextField();
        Jl_Usuario = new javax.swing.JLabel();
        Jt_Usuario = new javax.swing.JTextField();
        Jl_FechaNacimiento = new javax.swing.JLabel();
        Jp_Clave = new javax.swing.JPasswordField();
        Jl_Clave1 = new javax.swing.JLabel();
        jDate_Fecha = new com.toedter.calendar.JDateChooser();
        Btn_Nuevo = new javax.swing.JButton();
        Btn_Guardar = new javax.swing.JButton();
        Btn_Eliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setToolTipText("");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        Tbl_Datos.setBackground(new java.awt.Color(255, 255, 255));
        Tbl_Datos.setForeground(new java.awt.Color(51, 51, 51));
        Tbl_Datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tbl_Datos);

        Jl_Buscar.setForeground(new java.awt.Color(51, 51, 51));
        Jl_Buscar.setText("Buscar");

        Jt_Buscar.setBackground(new java.awt.Color(255, 255, 255));
        Jt_Buscar.setForeground(new java.awt.Color(51, 51, 51));
        Jt_Buscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Jl_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Jt_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Jt_Buscar)
                    .addComponent(Jl_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lista de usuarios", jPanel2);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Jl_Foto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Jl_Foto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(Jl_Foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 17, 150, 200));

        Btn_SubirFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/User.png"))); // NOI18N
        Btn_SubirFoto.setText("Subir foto");
        Btn_SubirFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SubirFotoActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_SubirFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 150, 30));

        Jl_Cedula.setText("Cedula");
        jPanel1.add(Jl_Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 17, 99, 30));
        jPanel1.add(Jt_Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 17, 375, 30));

        Jl_Nombre.setText("Nombre");
        jPanel1.add(Jl_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 53, 99, 30));
        jPanel1.add(Jt_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 53, 375, 30));

        Jl_Apellidos.setText("Apellidos");
        jPanel1.add(Jl_Apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 89, 99, 30));
        jPanel1.add(Jt_Apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 89, 375, 30));
        jPanel1.add(Jt_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 125, 375, 30));

        Jl_Correo.setText("Correo");
        jPanel1.add(Jl_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 125, 99, 30));

        Jl_Telefono.setText("Telefono");
        jPanel1.add(Jl_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 161, 99, 30));
        jPanel1.add(Jt_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 161, 375, 30));

        Jl_Usuario.setText("Usuario");
        jPanel1.add(Jl_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 197, 99, 30));
        jPanel1.add(Jt_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 197, 375, 30));

        Jl_FechaNacimiento.setText("Fecha de nacimiento");
        jPanel1.add(Jl_FechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 271, 280, 30));
        jPanel1.add(Jp_Clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 233, 375, 30));

        Jl_Clave1.setText("Contraseña");
        jPanel1.add(Jl_Clave1, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 240, 99, -1));
        jPanel1.add(jDate_Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 271, 200, 30));

        Btn_Nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Add.png"))); // NOI18N
        Btn_Nuevo.setText("Nuevo");
        jPanel1.add(Btn_Nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 325, 120, 30));

        Btn_Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Save.png"))); // NOI18N
        Btn_Guardar.setText("Guardar");
        jPanel1.add(Btn_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 325, 120, 30));

        Btn_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Delete.png"))); // NOI18N
        Btn_Eliminar.setText("Eliminar");
        jPanel1.add(Btn_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 325, 120, 30));

        jTabbedPane1.addTab("Usuarios", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_SubirFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SubirFotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_SubirFotoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Eliminar;
    private javax.swing.JButton Btn_Guardar;
    private javax.swing.JButton Btn_Nuevo;
    private javax.swing.JButton Btn_SubirFoto;
    private javax.swing.JLabel Jl_Apellidos;
    private javax.swing.JLabel Jl_Buscar;
    private javax.swing.JLabel Jl_Cedula;
    private javax.swing.JLabel Jl_Clave1;
    private javax.swing.JLabel Jl_Correo;
    private javax.swing.JLabel Jl_FechaNacimiento;
    private javax.swing.JLabel Jl_Foto;
    private javax.swing.JLabel Jl_Nombre;
    private javax.swing.JLabel Jl_Telefono;
    private javax.swing.JLabel Jl_Usuario;
    private javax.swing.JPasswordField Jp_Clave;
    private javax.swing.JTextField Jt_Apellidos;
    private javax.swing.JTextField Jt_Buscar;
    private javax.swing.JTextField Jt_Cedula;
    private javax.swing.JTextField Jt_Correo;
    private javax.swing.JTextField Jt_Nombre;
    private javax.swing.JTextField Jt_Telefono;
    private javax.swing.JTextField Jt_Usuario;
    private javax.swing.JTable Tbl_Datos;
    private com.toedter.calendar.JDateChooser jDate_Fecha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
